import Link from "next/link";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      <div className="max-w-3xl mx-auto px-4 py-16 md:py-24">
        <Link href="/" className="text-sm text-[#1a5c38] hover:underline mb-8 inline-block">&larr; Back to Home</Link>
        <h1 className="text-3xl md:text-4xl font-bold text-gray-900 mb-8">Terms of Service</h1>

        <div className="prose prose-gray max-w-none space-y-6 text-sm md:text-base leading-relaxed text-gray-700">
          <p>Last updated: July 1, 2026</p>

          <h2 className="text-xl font-bold text-gray-900 mt-8">1. Acceptance of Terms</h2>
          <p>By accessing or using BillFast ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.</p>

          <h2 className="text-xl font-bold text-gray-900 mt-8">2. Description of Service</h2>
          <p>BillFast is an online invoicing platform that allows users to create, customize, and download professional invoices in PDF format. Users may use the Service as guests or create an account for additional features.</p>

          <h2 className="text-xl font-bold text-gray-900 mt-8">3. Payment Terms</h2>
          <p>Each invoice creation requires a one-time payment of ₦300 (or equivalent in supported currencies). Payment is processed securely through Paystack. By initiating payment, you authorize BillFast to charge the applicable fee.</p>

          <h2 className="text-xl font-bold text-gray-900 mt-8">4. User Responsibilities</h2>
          <p>You agree to:</p>
          <ul className="list-disc pl-6 space-y-1">
            <li>Provide accurate information when creating invoices</li>
            <li>Not use the Service for any unlawful purpose</li>
            <li>Not attempt to circumvent the payment system</li>
            <li>Not upload malicious content or attempt to compromise the Service</li>
          </ul>

          <h2 className="text-xl font-bold text-gray-900 mt-8">5. Intellectual Property</h2>
          <p>The Service, including its design, code, and branding, is the property of BillFast. Invoices generated by users remain the property of the user, subject to payment of applicable fees.</p>

          <h2 className="text-xl font-bold text-gray-900 mt-8">6. Limitation of Liability</h2>
          <p>BillFast is provided "as is" without warranty of any kind. BillFast shall not be liable for any damages arising from the use or inability to use the Service, including but not limited to loss of data or business interruption.</p>

          <h2 className="text-xl font-bold text-gray-900 mt-8">7. Changes to Terms</h2>
          <p>We reserve the right to update these terms at any time. Continued use of the Service after changes constitutes acceptance of the new terms.</p>

          <h2 className="text-xl font-bold text-gray-900 mt-8">8. Contact</h2>
          <p>For questions about these terms, please contact us at <a href="mailto:support@billfast.ng" className="text-[#1a5c38] hover:underline">support@billfast.ng</a>.</p>
        </div>
      </div>
    </div>
  );
}
